ServerEvents.commandRegistry(event => {
  const { commands: Commands } = event

  event.register(
    Commands.literal('tribes_help')
      .requires(s => s.hasPermission(0))
      .executes(ctx => {
        const player = ctx.source.player
		player.tell("Tribe Commands:")
		player.tell("tribes_help: Messages you this text.")
		player.tell("tribes_list: Messages you all available tribes.")
		player.tell("tribes_status: Messages you your current tribe status.")
		player.tell("tribes_accept tribe: Accepts an invitation to a certain tribe.")
		player.tell("tribes_create name: Creates a tribe with the specified name.")
		player.tell("tribes_invite user: Invites the specified user to the tribe.")
		player.tell("tribes_promote user: Promotes the specified user to coleader.")
		player.tell("tribes_demote user: Demotes the specified user to the standart user.")
		player.tell("tribes_kick user: Kicks the specified user out of the tribe.")
		player.tell("tribes_rename name: Renames the tribe to the specified tribe.")
		player.tell("tribes_hide_advancements: Hides/Unhides the advancements of the tribe members to the public.")
		player.tell("tribes_hide_death: Hides/Unhides the deaths of the tribe members to the public.")
		player.tell("tribes_hide_nametag: Hides/Unhides the nametags of the tribe members to the public.")
		player.tell("tribes_color color: Changes the tribe color.")
		player.tell("-------------------------------------------------")
		player.tell("Available colors:")
		player.tell("- aqua")
		player.tell("- black")
		player.tell("- blue")
		player.tell("- dark_aqua")
		player.tell("- dark_blue")
		player.tell("- dark_gray")
		player.tell("- dark_green")
		player.tell("- dark_purple")
		player.tell("- dark_red")
		player.tell("- gold")
		player.tell("- gray")
		player.tell("- green")
		player.tell("- light_purple")
		player.tell("- red")
		player.tell("- reset")
		player.tell("- white")
		player.tell("- yellow")
		// Utils.server.runCommand(`say ${player} halo`)
        return 1
      })
  )
})
